name: Publish Package

on:
  release:
    types: [ released ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    name: Tests
    uses: ./.github/workflows/PackageTest.yml
    secrets: inherit

  publish-package:
    name: Publish Distribution
    needs: run-tests
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - host: https://py00.crc.pitt.edu
            environment: publish-h2p
          - host: https://upload.pypi.org/legacy/
            environment: publish-pypi

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      # Get the new package version from the release tag
      # Git release tags are expected to start with "refs/tags/v"
      - name: Set package version
        run: |
          release_tag=${{github.ref}}
          poetry version "${release_tag#refs/tags/v}"

      - name: Build package
        run: poetry build -v

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          repository-url: ${{ matrix.host }}
          user: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASSWORD }}
