name: Run Tests

on:
  workflow_dispatch:
  push:

jobs:
  python_tests:
    name: Run Python tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Update Python environment
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m unittest
          coverage report
          coverage xml -o report_${{ matrix.python-version }}.xml

      # Report test coverage to codacy for the python version being tested
      - name: Report partial coverage results
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l Python -r report_${{ matrix.python-version }}.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  codacy-coverage-reporter:
    name: Report code coverage
    runs-on: ubuntu-latest
    needs: python_tests
    steps:

      # Tell codacy we are done reporting test coverage
      - name: Finish reporting coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) final
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
